name: CI/CD Pipeline

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]

jobs:
  # Lint and Code Quality
  lint:
    runs-on: ubuntu-latest
    name: Code Quality Check

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run ESLint
      run: npm run lint

    - name: Check for security vulnerabilities
      run: npm audit --audit-level moderate

  # Unit and Integration Tests
  test:
    runs-on: ubuntu-latest
    name: Unit & Integration Tests

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run unit tests
      run: npm run test:unit

    - name: Run integration tests
      run: npm run test:integration

    - name: Run UI addition tests
      run: npm run test:ui-addition

    - name: Generate test coverage
      run: npm run test:coverage

    - name: Validate coverage thresholds for new modules
      run: npm run test:coverage:validate

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage/lcov.info
        flags: unittests
        name: codecov-umbrella

  # End-to-End Tests
  e2e:
    runs-on: ubuntu-latest
    name: End-to-End Tests

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run: npm run test:e2e

    - name: Upload Playwright Report
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: test-results/playwright-report/
        retention-days: 30

  # Cross-browser Testing
  cross-browser:
    runs-on: ubuntu-latest
    name: Cross-Browser Testing
    needs: [lint, test]

    strategy:
      matrix:
        browser: [chromium, firefox, webkit]
        feature-flag: ['enabled', 'disabled', 'partial']

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Set feature flag environment
      run: |
        case "${{ matrix.feature-flag }}" in
          "enabled")
            echo "FEATURE_FLAGS={\"ui-addition\":true,\"enhanced-icons\":true,\"simplified-theme-toggle\":true}" >> $GITHUB_ENV
            ;;
          "disabled")
            echo "FEATURE_FLAGS={\"ui-addition\":false}" >> $GITHUB_ENV
            ;;
          "partial")
            echo "FEATURE_FLAGS={\"ui-addition\":true,\"enhanced-icons\":false,\"simplified-theme-toggle\":true}" >> $GITHUB_ENV
            ;;
        esac

    - name: Run tests on ${{ matrix.browser }} with ${{ matrix.feature-flag }} flags
      run: npx playwright test --project=${{ matrix.browser }} --grep="UI Addition|ui-addition"
      env:
        FEATURE_FLAG_CONFIG: ${{ env.FEATURE_FLAGS }}

    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-results-${{ matrix.browser }}-${{ matrix.feature-flag }}
        path: test-results/
        retention-days: 30

  # Accessibility Testing
  accessibility:
    runs-on: ubuntu-latest
    name: Accessibility Testing

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright and axe
      run: |
        npx playwright install --with-deps
        npm install @axe-core/playwright

    - name: Run standard accessibility tests
      run: npx playwright test --grep="accessibility"

    - name: Run UI addition accessibility tests
      run: npm run test:accessibility:ui-addition

    - name: Test icon accessibility across themes
      run: npm run test:accessibility:icons

    - name: Test theme toggle accessibility
      run: npm run test:accessibility:theme-toggle

    - name: Upload accessibility report
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: accessibility-report
        path: test-results/accessibility/
        retention-days: 30

  # Security Scanning
  security:
    runs-on: ubuntu-latest
    name: Security Scan

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run security audit
      run: npm audit --audit-level moderate

    - name: Run Snyk security scan
      uses: snyk/actions/node@master
      continue-on-error: true
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --severity-threshold=high

  # Performance Testing
  performance:
    runs-on: ubuntu-latest
    name: Performance Testing

    strategy:
      matrix:
        scenario: ['baseline', 'with-icons', 'feature-disabled']

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Install Lighthouse CI
      run: npm install -g @lhci/cli@0.12.x

    - name: Configure performance scenario
      run: |
        case "${{ matrix.scenario }}" in
          "baseline")
            echo "LIGHTHOUSE_CONFIG=baseline" >> $GITHUB_ENV
            ;;
          "with-icons")
            echo "LIGHTHOUSE_CONFIG=ui-addition-enabled" >> $GITHUB_ENV
            echo "FEATURE_FLAGS={\"ui-addition\":true,\"enhanced-icons\":true}" >> $GITHUB_ENV
            ;;
          "feature-disabled")
            echo "LIGHTHOUSE_CONFIG=ui-addition-disabled" >> $GITHUB_ENV
            echo "FEATURE_FLAGS={\"ui-addition\":false}" >> $GITHUB_ENV
            ;;
        esac

    - name: Run icon loading performance tests
      run: npm run test:performance:icons
      env:
        FEATURE_FLAG_CONFIG: ${{ env.FEATURE_FLAGS }}

    - name: Run Lighthouse CI for ${{ matrix.scenario }}
      run: |
        npm run dev &
        sleep 10
        lhci autorun --config=lighthouserc-${{ matrix.scenario }}.js --upload.target=temporary-public-storage
      env:
        LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
        FEATURE_FLAG_CONFIG: ${{ env.FEATURE_FLAGS }}

    - name: Upload performance results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: lighthouse-results-${{ matrix.scenario }}
        path: .lighthouseci/
        retention-days: 30

  # Visual Regression Testing
  visual-regression:
    runs-on: ubuntu-latest
    name: Visual Regression Testing
    needs: [test]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run visual regression tests
      run: npm run test:visual-regression

    - name: Upload visual diff artifacts
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: visual-regression-diffs
        path: test-results/visual-regression/
        retention-days: 30

  # Feature Flag Testing
  feature-flags:
    runs-on: ubuntu-latest
    name: Feature Flag Testing
    needs: [test]

    strategy:
      matrix:
        environment: ['development', 'staging', 'production']
        flag-combination: ['all-enabled', 'all-disabled', 'icons-only', 'theme-only', 'mixed']

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Configure feature flags for ${{ matrix.environment }}
      run: npm run test:feature-flags:configure -- --env=${{ matrix.environment }} --flags=${{ matrix.flag-combination }}

    - name: Run feature flag tests
      run: npm run test:feature-flags -- --env=${{ matrix.environment }} --flags=${{ matrix.flag-combination }}

    - name: Upload feature flag test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: feature-flag-results-${{ matrix.environment }}-${{ matrix.flag-combination }}
        path: test-results/feature-flags/
        retention-days: 30

  # Deployment (on main branch only)
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Production
    needs: [lint, test, e2e, cross-browser, accessibility, security, visual-regression, feature-flags]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build application
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        exclude_assets: 'node_modules,tests,.github'

  # Notification
  notify:
    runs-on: ubuntu-latest
    name: Notify Results
    needs: [lint, test, e2e, cross-browser, accessibility, security, performance, visual-regression, feature-flags]
    if: always()

    steps:
    - name: Notify on success
      if: ${{ needs.test.result == 'success' && needs.e2e.result == 'success' }}
      run: echo "✅ All tests passed successfully!"

    - name: Notify on failure
      if: ${{ needs.test.result == 'failure' || needs.e2e.result == 'failure' }}
      run: |
        echo "❌ Tests failed!"
        exit 1